port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
external-ui: ui

# DNS é…ç½®
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
    - 94.140.14.14
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://dns.adguard-dns.com/dns-query

# åœ°åŒºè‡ªåŠ¨æµ‹é€Ÿåˆ†ç»„
proxy-groups:
  - name: æ‰‹åŠ¨
    type: select
    proxies:
      - US
      - HK
      - SG
      - JP
      - UN
    icon: https://raw.githubusercontent.com/OpenSourceVision/icon/refs/heads/main/other/Default.png

  - name: US
    type: url-test
    include-all: true
    filter: '.*(ç¾å›½|ç¾åœ‹|US|United States|America|USA|ç¾|ğŸ‡ºğŸ‡¸|çº½çº¦|æ´›æ‰çŸ¶|æ—§é‡‘å±±|è¥¿é›…å›¾|èŠåŠ å“¥|è¾¾æ‹‰æ–¯|Miami|Atlanta|Denver|Phoenix).*'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    icon: https://raw.githubusercontent.com/OpenSourceVision/icon/refs/heads/main/flag/US.png

  - name: HK
    type: url-test
    include-all: true
    filter: '.*(é¦™æ¸¯|æ¸¯|HK|Hong Kong|HongKong|ğŸ‡­ğŸ‡°|æ·±æ¸¯|ä¸­æ¸¯).*'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    icon: https://raw.githubusercontent.com/OpenSourceVision/icon/refs/heads/main/flag/HK.png

  - name: SG
    type: url-test
    include-all: true
    filter: '.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore|ğŸ‡¸ğŸ‡¬).*'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    icon: https://raw.githubusercontent.com/OpenSourceVision/icon/refs/heads/main/flag/SG.png

  - name: JP
    type: url-test
    include-all: true
    filter: '.*(æ—¥æœ¬|æ—¥|JP|Japan|ğŸ‡¯ğŸ‡µ|ä¸œäº¬|å¤§é˜ª|Tokyo|Osaka|Nagoya|åå¤å±‹).*'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    icon: https://raw.githubusercontent.com/OpenSourceVision/icon/refs/heads/main/flag/JP.png

  - name: UN
    type: url-test
    include-all: true
    filter: '.*'
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    icon: https://raw.githubusercontent.com/OpenSourceVision/icon/refs/heads/main/flag/UN.png

# è§„åˆ™é›†æä¾›è€…
rule-providers:
  # å¹¿å‘Šè§„åˆ™
  ad:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/earoftoast/clash-rules/main/AD.yaml"
    path: ./rules/ad.yaml
    interval: 86400
    format: yaml
  privacy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/earoftoast/clash-rules/main/EasyPrivacy.yaml"
    path: ./rules/privacy.yaml
    interval: 86400
    format: yaml

  # åŸºç¡€è§„åˆ™
  private:
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml
    path: ./ruleset/private.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http
  
  cn_ip:
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml
    path: ./ruleset/cn_ip.yaml
    behavior: ipcidr
    interval: 86400
    format: yaml
    type: http
  
  cn_domain:
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml
    path: ./ruleset/cn_domain.yaml
    behavior: domain
    interval: 86400
    format: yaml
    type: http  

# è§„åˆ™å¼•ç”¨
rules:
  - RULE-SET,ad,REJECT
  - RULE-SET,privacy,REJECT
  - RULE-SET,private,DIRECT
  - RULE-SET,cn_domain,DIRECT
  - RULE-SET,cn_ip,DIRECT
  - MATCH,æ‰‹åŠ¨